#!/bin/sh /etc/rc.common
# Copyright (C) 2009 OpenWrt.org

START=61

start() {
	mkdir -p /var/tmp
	mkdir -p /etc/krb5kdc
	
	/usr/sbin/krb5kdc
	/usr/sbin/kadmind
}

stop() {
	killall kadmind 2> /dev/null
	killall krb5kdc 2> /dev/null
}
